= bigmailer: OpenBSD _smtpctl spf walk_ starter kit

When the internet was young, everybody ran their own mail server - singular.
SPAM came along. GreyListing was one of several good responses to it.
Then big mailers grew multiple servers AND were too lazy to implement
"server affinity" - keep trying to send a given message from a given IP.
Instead, they send a message from a randomly-chosen server each time they retry
after the greylisting delays it... 
This broke greylisting, as the message would come from a different IP each
time, which would get added to the ever-growing grey list, but the message
would rarely get through.

Fortunately, there's a solution to this problem too. Sender Policy Framework
(SPF) requires mail senders to list all the hosts that their mail can come
from. So now, smtpd's helper program smtpctl has the capability to
read the SPF information from each of a list of "big mailer" domains, and
list them in a form which our pfctl can accept.

So assuming you have a file called _bigmailers.txt_
(which you can get from here), you can just do

	smtpctl spf walk < /etc/mail/bigmailers.txt | pfctl -t spf-white -T add -f -

Assuming you have pf redirect incoming SMTP into greylisting, and you have
a filter rule that bypasses hosts in the table spf-white, mail from
the big mailers will come right in. Along with any SPAM they send, of course.


